services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mypass
    networks:
      - postgres_network
  backend:
    ports:
      - 3000:3000
    build:
      dockerfile: Dockerfile
      context: server/
      target: builder
    depends_on:
      - db
    networks:
      - postgres_network
  frontend:
    ports:
    - 5173:5173
    build:
      dockerfile: Dockerfile
      context: client/
      target: dev
    networks:
      - postgres_network
      

networks:
  postgres_network:
    driver: bridge
